[package]
name = "MirrorSphere"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.26"
toml = "0.8.20"
anyhow = "1.0.97"
dashmap = "6.1.0"
tracing = "0.1.41"
privilege = "0.3.0"
thiserror = "2.0.12"
tracing-appender = "0.2.3"
fs4 = { version = "0.13.0", features = ["tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.218", features = ["derive"] }
sqlx = { version = "0.8.3", features = [ "runtime-tokio", "sqlite", "uuid", "derive" ] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
serde_json = "1.0.139"
futures = "0.3.31"
async-trait = "0.1.87"
tokio-stream = "0.1.17"
sha3 = "0.10.8"
sha2 = "0.10.8"
blake2 = "0.10.6"
digest = "0.10.7"
md-5 = "0.10.6"


[dependencies.blake3]
version = "1.6.1"
features = ["traits-preview"]

[dependencies.uuid]
version = "1.13.1"
features = ["v4", "fast-rng", "serde"]

[target.'cfg(windows)'.windows-core]
version = "0.60.1"

[target.'cfg(windows)'.dependencies.windows-acl]
version = "0.3.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.60.0"
features = ["Win32", "Win32_Security", "Win32_Storage", "Win32_System", "Win32_Storage_FileSystem", "Win32_System_Memory", "Win32_Security_Authorization"]

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.59.0"
features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Registry", "Win32_System_Com", "Win32_UI_WindowsAndMessaging"]
