[package]
name = "MirrorSphere"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
toml = "0.8.20"
anyhow = "1.0.95"
dashmap = "6.1.0"
tracing = "0.1.41"
privilege = "0.3.0"
thiserror = "2.0.11"
tracing-appender = "0.2.3"
fs4 = { version = "0.12", features = ["tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
sqlx = { version = "0.8.3", features = [ "runtime-tokio", "sqlite", "uuid", "derive" ] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
serde_json = "1.0.133"
futures = "0.3.31"
async-trait = "0.1.86"
flume = "0.11.1"
tokio-stream = "0.1.16"

[dependencies.uuid]
version = "1.13.1"
features = ["v7", "fast-rng", "serde"]

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.59.0"
features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Registry", "Win32_System_Com", "Win32_UI_WindowsAndMessaging"]
