[package]
name = "MirrorSphere"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.19"
anyhow = "1.0.95"
tracing = "0.1.41"
thiserror = "2.0.11"
privilege = "0.3.0"
lazy_static = "1.5.0"
tracing-appender = "0.2.3"
fs4 = { version = "0.12", features = ["tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
time = { version = "0.3.37", features = ["macros"] }
serde = { version = "1.0.217", features = ["derive"] }
sqlx = { version = "0.8.3", features = [ "runtime-tokio", "sqlite" ] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
log = "0.4.22"

[dependencies.uuid]
version = "1.12.1"
features = ["v7", "fast-rng", "serde"]

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.59.0"
features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Registry", "Win32_System_Com", "Win32_UI_WindowsAndMessaging"]
