[package]
name = "MirrorSphere"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.19"
tracing = "0.1.40"
thiserror = "2.0.3"
lazy_static = "1.5.0"
tracing-appender = "0.2.3"
tokio = { version = "1.41.1", features = ["full"] }
time = { version = "0.3.36", features = ["macros"] }
serde = { version = "1.0.215", features = ["derive"] }
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "sqlite" ] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
