[package]
name = "MirrorSphere"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
lazy_static = "1.5.0"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
tokio = { version = "1.41.1", features = ["full"] }
time = { version = "0.3.36", features = ["macros"] }