name: PR Check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-check:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Configure Cargo for cross-compilation
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << EOF
          [target.x86_64-pc-windows-gnu]
          linker = "x86_64-w64-mingw32-gcc"
          ar = "x86_64-w64-mingw32-ar"
          EOF

      - name: Run Clippy
        run: cargo clippy

      - name: Build Linux (debug)
        run: cargo build --verbose

      - name: Build Windows (debug)
        run: cargo build --target x86_64-pc-windows-gnu --verbose

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: mirrorsphere-linux-debug
          path: target/debug/MirrorSphere
          retention-days: 90

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: mirrorsphere-windows-debug
          path: target/x86_64-pc-windows-gnu/debug/MirrorSphere.exe
          retention-days: 90